apps/users_app/urls.py
from django.conf.urls import url
from . import views


# TEMPLATE URLS
app_name = 'users_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login')
]

main/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from apps.users_app import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^users_app/', include('apps.users_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/', views.special, name='special'),
]

apps/users_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    # extends class and allows us to add more attributes to actual user
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional classes
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)


    def __str__(self):
    	# username is attribute of user object now
    	return self.user.username

apps/users_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta():
		model = User
		fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta():
		model = UserProfileInfo
		fields = ('portfolio_site', 'profile_pic')

apps/users_app/views.py
from django.shortcuts import render, HttpResponse, redirect
from .forms import UserProfileInfoForm, UserForm

from django.urls import reverse
# view to require user be logged in
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'users_app/index.html')

@login_required
def special(request):
	return HttpResponse("You are logged in, nice!")

# login decorator (has to be directly on top)
@login_required
def user_logout(request):
	logout(request)
	return redirect(reverse('index'))


def register(request):

    # assume user not registered
    registered = False

    if request.method == "POST":
        # grab information off of forms
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # check if both forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            # grab from base user form
            user = user_form.save()
            # hash password
            user.set_password(user.password)
            # save hashed password to db
            user.save()

            # grab profile form
            profile = profile_form.save(commit=False)
            profile.user = user

            # check if picture before we save
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            # save model
            profile.save()

            # registration successful
            registered = True

        # print out errors
        else:
            print(user_form.errors, profile_form.errors)

    # request wasn't an HTTP request; didn't post a nything
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    }

    return render(request, 'users_app/registration.html', context)


def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		# built in auth function, authenticate user
		user = authenticate(username=username,password=password)

		# if user is active, log them in
		if user:
			if user.is_active:
				login(request, user)
				return redirect(reverse('index'))
			else:
				return HttpResponse("Account not active")
		else:
			print("Someone tried to login and failed!!!")
			print("Username: {} and password {}".format(username, password))
			return HttpResponse("Invalid login details supplied!")
	else:
		return render(request, "users_app/login.html", {})

templates/users_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <ul class="navbar-nav mr-auto">
		      <li class="nav-item active">
		        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
		      </li>
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'users_app:register' %}">Register</a>
		      </li>
		      {% if user.is_authenticated %}
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
		      </li>
		      {% else %}
		      <li class="nav-item">
		        <a class="nav-link" href="{% url 'users_app:user_login' %}">Login</a>
		      </li>
		      {% endif %}
		  	</ul>
        </div>
    </nav>

	<div class="container">
		
		{% block body_block %}
		{# Anything outside of this will be inherited if you extend #}
		{% endblock %}

	</div>

</body>

</html>

templates/users_app/index.html
{% extends "users_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
	<h1>Index Page</h1>
</div>

{% endblock %}

templates/users_app/login.html
{%  extends 'users_app/base.html' %}
{% block body_block %}

	<div class="jumbotron">
		<h1>Please Login</h1>
		<form action="{% url 'users_app:user_login' %}" method="POST">
			{% csrf_token %}
			<label for="username">Username:</label>
			<input type="text" name="username" placeholder="Enter Username">

			<label for="password">Password:</label>
			<input type="password" name="password">

			<input type="submit" name="" value="Login">
		</form>
	</div>

{% endblock %}

templates/users_app/registration.html
{% extends 'users_app/base.html' %}

{% load static %}

{% block body_block %}

<div class="jumbotron">
	{% if registered %}
		<h1>Thank you for registering!</h1>
	{% else %}
		<h1>Register Here!</h1>
		<h3>Fill out the form:</h3>

		<form enctype="multipart/form-data" method="POST">
			{% csrf_token %}
			{{  user_form.as_p }}
			{{ profile_form.as_p }}
			<input type="submit" value="Register">
		</form>

	{% endif %}
</div>

{% endblock %}